baseurl: "https://dataoceanlab.github.io/spatial-api-2021"
title: "International Workshop on APIs and Libraries for Geospatial Data Science@ACM SIGSPATIAL 2021"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "SpatialAPI@ACM SIGSPATIAL 2021"
  Description: "International Workshop on APIs and Libraries for Geospatial Data Science@ACM SIGSPATIAL 2020"
  Date: "November 2, 2021, Beijing Time"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Online"
  Address: "Online"
  City:  "Beijing"
  State: "China"
  Images: ["/img/logo.png"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - location
    - cfp
    - deadline
    - organizer
    - speakers
    # - schedule
    #- contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Tutorials"
    organizer: "Organization Committee"
    speakers: "Speakers"
    schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    # contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now"
    link: ""

  intro:
    text: "The 3rd ACM SIGSPATIAL International Workshop on APIs and Libraries for Geospatial Data Science (SpatialAPI 2021) is to provide students and researchers with hands-on experience with useful APIs and libraries related to geospatial data science, spanning from spatial big data management to advanced analytics enabled by machine learning, optimization, and more. At the same time, it gives an opportunity for API providers to reach out to targeted audiences who can benefit from their APIs. The API providers will be able to get direct feedback for their users to understand how to further improve their APIs and make them more user-friendly. The tutorials will be done in a classroom-style setting where the audience will bring their laptops to follow the directions of the presenter."

  cfp:
    text: "The workshop is calling for tutorial proposals from the community. Each accepted tutorial will have two 45-minute sessions to conduct their hands-on tutorial. In addition, each presenter will have the
opportunity to give a teaser presentation of 5 minutes to attract the audience to attend their tutorial. Interested participants should submit a tutorial proposal in ACM format
(https://www.acm.org/publications/proceedings-template). This proposal must be no more than 2 pages and contain the content listed in the PDF version of CFP."
    url: "https://dataoceanlab.github.io/spatial-api-2021/files/CFP21.pdf"
    keywords: [""]

  organizer:
    pc_chair: ["Yiqun Xie (University of Maryland)", 
    "Jia Yu (Washington State University, Apache Software Foundation)"]
    pc_member: ["Peter Baumann (Jacobs University Bremen)", "Ahmed Eldawy (University of California, Riverside)", "Amr Magdy (University of California, Riverside)", "Janet Reyes (University of California, Riverside)", "Ibrahim Sabek (Massachusetts Institute of Technology)", "Martin Werner (Technical University of Munich)"]

  deadline:
    submission: "August 31, 2021 (anywhere on earth)"
    notification: "September 25, 2021 (anywhere on earth) (extended)"
    camera: "To be announced"
    workshopdate: "November 2, 2021"
    submissionsite: "https://easychair.org/my/conference?conf=spatialapi21"

  Speakers: 
    - name: "SafeGraph"
      photo: "https://assets-global.website-files.com/5baafc2653bd67278f206724/5e71e3904626f11bd4f00ea5_safegraph-logo.svg"
      bio: "SafeGraph’s places dataset includes a breadth of information about physical places in the US, UK and Canada. This includes core location data, spatial hierarchy metadata, place traffic data, and more."
      company: "SafeGraph"
      talk: 
        title: "This is an invited talk"
        href: ""
      # link:
      #   twitter: "http://twitter.com/linus"
      #   github: "http://github.com/linus"
      #   linkedin: "http://linkedin.com/linus"